---

- name: Create application log directory
  file:
    path: "{{ docker_mount_directory }}/{{ application_name }}/log"
    state: directory
    mode: 0757

- name: Create mysql backup directory
  file:
    path: "{{ docker_mount_directory }}/{{ application_name }}/mysql/backup"
    state: directory
    mode: 0757

- name: Get application compose files from github
  git:
    repo: https://github.com/tekkon7278/cms-compose.git
    dest: "{{ docker_compose_directory }}/{{ application_name }}"
    
- name: Put compose env file
  template:
    src: compose/.env
    dest: "{{ docker_compose_directory }}/{{ application_name }}/.env"

- name: Put laravel env file
  template:
    src: php/.env
    dest: "{{ docker_compose_directory }}/{{ application_name }}/php/files/.env"

- name: Put nginx conf file
  template:
    src: nginx/proxy.conf
    dest: "{{ docker_compose_directory }}/{{ application_name }}/nginx/files/conf.d/proxy.conf"

- name: Execute docker compose
  shell:
    cmd: docker compose up -d
    chdir: "{{ docker_compose_directory }}/{{ application_name }}/"

- name: Create application service
  copy:
    src: docker.{{ application_name }}.service
    dest: /etc/systemd/system/
    mode: 0644