---

- name: Set Let's Encrypt auto update cron
  cron:
    name: Let's Encrypt auto update
    minute: '1'
    hour: '3'
    day: '1'
    job: "docker compose -f {{ docker_compose_directory }}/{{ application_name }}/docker-compose.yml run certbot"

- name: Set MySQL backup cron
  cron:
    name: MySQL backup
    minute: '1'
    hour: '4'
    job: "docker compose -f {{ docker_compose_directory }}/{{ application_name }}/docker-compose.yml exec mysql /srv/backup/dump.sh"
